### ISSUE TITLE
How to insert multiple values into a key via command?

### ISSUE THREAD

**Issue by Neeef** [rjt-rockx/sapphyr#16]
Regarding the shop, I'm attempting to make a command to add roles, but .set only sets a value. Insert one requires me to insert into a collection itself, and that's not what I'm trying to do.

**Comment by rjt-rockx** [comment]
Pass an object as the value if you want the object to be stored under a key, or pass the object directly and it'll set all the keys of that object to their values. 

Example:
```js
ctx.db.set("this", { foo: "bar", baz: 123 });
```
Or even:
```js
ctx.db.set({ this: { foo: "bar", baz: 123 }});
```

**Comment by rjt-rockx** [comment]
Multiple values can be set similarly
```js
ctx.db.set({beta:true, linkdetection:{ enabled:true }, permissions: [] });
```

**Comment by rjt-rockx** [comment]
However things like
```js
ctx.db.set("beta", true, "permissions", []);
```
won't work because they're different arguments. 

You can set multiple values individually though: 
```js
ctx.db.set("beta", true);
ctx.db.set("permissions", []);
```

**Comment by rjt-rockx** [comment]
Lemme know if this didn't answer the question.

**Comment by Neeef** [comment]
regarding multiple values individually, I want to make it so whenever xyz is called(command) it adds an argument as a value, without fully replacing the over values. so with "ctx.db.set("key", [])" can I just set other things into the key value array without replacing them all?

**Comment by Neeef** [comment]
I've done maybe 20 tries all different of trying to insert a value into the key. but they all fail.

**Comment by rjt-rockx** [comment]
```js
let abc = await ctx.db.get("somearrayvalue"); // ["foo", "bar"]
abc.push("baz"); // ["foo", "bar", "baz"]
await ctx.db.set("somearrayvalue", abc); 
```

**Comment by Neeef** [comment]
awesome thanks.
