### ISSUE TITLE
Sapphyr VPS not storing nadekoconnector configuration on external database. 

### ISSUE THREAD

**Issue by Neeef** [rjt-rockx/sapphyr#19]
_nc does not store the configuration, there does not seem to be any syntax issues.

**Comment by Neeef** [comment]
https://pastebin.com/SmKam4q7

That is the exact datahandler my testing variant is hosting and it runs fine.

**Comment by Neeef** [comment]
TypeError: this.datahandler.getOrCreateGlobal is not a function

Issue detected when baseCommand is updated, not when globaldatahandler are added, possibly an issue with baseCommand

**Comment by rjt-rockx** [comment]
globalDataHandler had nothing to do with this, the issue was with datahandler missing a line.
